# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.
require 'securerandom'

def secure_token
  token_file = Rails.root.join('.secret')
  if File.exist?(token_file)
    # Use the existing token.
    File.read(token_file).chomp
  else
    # Generate a new token and store it in token_file.
    token = SecureRandom.hex(64)
    File.write(token_file, token)
    token
  end
end

SampleApp::Application.config.secret_key_base = secure_token
# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b9425c226d14e4c60484422b38dd52f84530cfecee89c6ad4e8a312f4401add8a3d98d91260c2626b85c720f0b3249ad0067efc2fc4a444c8a659451733f360

test:
  secret_key_base: 36d9f9afd18898b1fee3a1db13d02917ffc338b7fbd4360ff0a9f82c0d426a3d214bd4931d50ce7a64cdc4f764d67c6b8a13a1d09078111b991beeb3e4892797

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
